<a href="https://colab.research.google.com/github/sarthakd99/NLA_libraries/blob/main/Lib_comparison.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import time 
import numpy as np
import torch
import tensorflow as tf

# Matrix Multiplication in Pytorch
1. torch.matmul
2. torch.mm
3. torch.bmm (@ operator)

# torch.matmul(input, other) 

### a. If both tensors are 1-dimensional, the dot product (scalar) is returned

In [ ]:
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
print("a = ", tensor1)
print("b = ",tensor2)
result = torch.matmul(tensor1, tensor2)
print("Matrix Multiplication")
print("result = ", result)
print("result shape = ", result.shape)

a =  tensor([-1.9600, -0.0771, -1.1283])
b =  tensor([-0.0920, -0.0374,  0.6208])
Matrix Multiplication
result =  tensor(-0.5172)
result shape =  torch.Size([])


### b. If both arguments are 2-dimensional, the matrix-matrix product is returned.

In [ ]:
tensor1 = torch.randn(2,2)
tensor2 = torch.randn(2,2)
print("a = ", tensor1)
print("b = ",tensor2)
result = torch.matmul(tensor1, tensor2)
print("Matrix Multiplication")
print("result = ", result)
print("result shape = ", result.shape)

a =  tensor([[-0.5378, -0.7393],
        [ 1.1999,  0.9112]])
b =  tensor([[1.0585, 0.9816],
        [0.9476, 0.2258]])
Matrix Multiplication
result =  tensor([[-1.2699, -0.6949],
        [ 2.1335,  1.3836]])
result shape =  torch.Size([2, 2])


###c. If the first argument is 2-dimensional and the second argument is 1-dimensional, the matrix-vector product is return


In [ ]:
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)
print("a = ", tensor1)
print("a.shape = ", tensor1.shape)
print("b = ",tensor2)
print("b.shape = ", tensor2.shape)
result = torch.matmul(tensor1, tensor2)
print("Matrix Multiplication")
print("result = ", result)
print("result shape = ", result.shape)

a =  tensor([[ 0.7430, -1.0386, -0.6316,  1.1493],
        [-0.9619, -0.0637,  0.8153, -0.4538],
        [ 0.9085,  1.5303,  0.2113,  0.2086]])
a.shape =  torch.Size([3, 4])
b =  tensor([-0.4484, -0.1205, -0.7371,  0.3574])
b.shape =  torch.Size([4])
Matrix Multiplication
result =  tensor([ 0.6682, -0.3241, -0.6729])
result shape =  torch.Size([3])


###d. Batch multiplication
### We can consider there are 10 matrices of size $(3 × 4)$ each, and we mulitply them with the $(4 \times 5)$ indiviusally (10 times) so we get an output of $(10 \times 3 \times 5)$ 

In [ ]:
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4, 5)
print("a = ", tensor1)
print("a.shape = ", tensor1.shape)
print("b = ",tensor2)
print("b.shape = ", tensor2.shape)
result = torch.matmul(tensor1, tensor2)
print("Matrix Multiplication")
print("result = ", result)
print("result shape = ", result.shape)

a =  tensor([[[-1.5178e+00,  1.8911e-01,  7.1672e-01,  4.0953e-01],
         [-1.2885e+00, -1.9387e+00,  4.1649e-01, -5.7361e-01],
         [-3.8721e-02, -3.4056e+00, -1.0182e+00, -5.2486e-01]],

        [[-6.6768e-01, -2.5695e+00, -7.6751e-01,  2.9932e-01],
         [-4.3196e-01,  7.7619e-01, -1.1394e+00,  6.1207e-01],
         [-2.1119e+00,  2.3457e-02, -1.7494e+00, -9.0651e-01]],

        [[-1.2016e+00,  6.4071e-01,  2.5014e+00,  1.2764e+00],
         [ 1.4917e+00, -6.1797e-01, -2.0771e-01,  3.9639e-01],
         [-1.8710e-01, -1.0319e-02,  2.0566e+00, -1.0867e+00]],

        [[-2.0789e-02, -6.0029e-03, -1.2130e-04, -1.8311e-01],
         [-1.9235e-02, -2.0557e+00,  1.3564e+00,  4.0022e-01],
         [-1.5469e+00, -3.2519e-01,  1.8983e-01,  5.0507e-01]],

        [[ 9.1842e-01,  1.0978e+00,  1.9762e-01,  4.7936e-02],
         [ 1.6011e+00,  8.3670e-01, -7.8729e-01,  5.3989e-03],
         [-2.3281e+00, -8.5402e-01, -6.4492e-02, -1.4133e-01]],

        [[ 1.7167e-03,  1.6303e-01,  1.6

### e. Batched matrix x broadcasted vector

In [ ]:
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)
print("a = ", tensor1)
print("a.shape = ", tensor1.shape)
print("b = ",tensor2)
print("b.shape = ", tensor2.shape)
result = torch.matmul(tensor1, tensor2)
print("Matrix Multiplication")
print("result = ", result)
print("result shape = ", result.shape)

a =  tensor([[[ 2.1951, -0.7033, -1.0281,  0.9812],
         [-1.4087, -0.2304,  0.1978,  1.7817],
         [-2.2070, -0.5178,  1.6159,  1.3061]],

        [[ 1.0488, -0.1014, -0.1316, -0.0131],
         [ 0.2175, -1.6450, -0.8306,  0.4784],
         [-0.6471, -0.4271, -0.9098,  0.2213]],

        [[ 0.7702, -0.6468, -0.6912, -2.2399],
         [-0.6797, -0.0697, -0.4725,  1.6453],
         [ 0.7231,  0.3355, -0.3583,  0.5908]],

        [[ 1.0870,  0.0400,  0.6138,  0.4343],
         [ 1.5825, -0.7033,  1.4403,  0.0310],
         [ 0.8888, -1.2603, -0.1909, -2.4673]],

        [[-0.3686,  0.3740, -0.3624,  1.3859],
         [-0.2411, -0.4875, -0.8253, -0.5790],
         [-0.1424,  0.1419,  0.4314, -0.9126]],

        [[-1.6405, -1.2806,  0.0199, -0.2511],
         [-0.6470, -2.0398, -2.0527, -0.4711],
         [ 2.3107, -0.3647,  0.4279,  1.7295]],

        [[ 0.9408, -0.7001,  1.9401, -0.5736],
         [ 0.3623,  0.8928, -0.9771, -0.3604],
         [-0.8690,  1.4390, -0.3395, -0.856

# 2. torch.mm

- This function doesn't allow broadcasting
- If input is a $(n x m)$ tensor, mat2 is a $(m x p)$ tensor, out will be a $(n x p)$ tensor
- Requires both inputs to be matrix

In [ ]:
tensor1 = torch.randn(3,2)
tensor2 = torch.randn(2,4)
print("a = ", tensor1)
print("b = ",tensor2)
result = torch.mm(tensor1, tensor2)
print("Matrix Multiplication")
print("result = ", result)
print("result shape = ", result.shape)

a =  tensor([[ 2.6638,  1.5010],
        [ 0.7859,  0.4591],
        [ 0.6587, -1.9467]])
b =  tensor([[-0.2277, -0.3544, -0.4251, -0.4128],
        [-0.4655, -0.0213,  1.5327, -0.5774]])
Matrix Multiplication
result =  tensor([[-1.3051, -0.9760,  1.1683, -1.9663],
        [-0.3926, -0.2883,  0.3696, -0.5895],
        [ 0.7562, -0.1919, -3.2637,  0.8522]])
result shape =  torch.Size([3, 4])


# 3. torch.bmm

- This function doesn't allow broadcasting
- Performs a batch matrix-matrix product of matrices stored in input and mat2.
- input and mat2 must be 3-D tensors each containing the same number of matrices. 
- If input is a $( b × n × m )$ tensor, mat2 is a $(b × m × p)$ tensor, out will be a $(b × n × p)$ tensor.

In [ ]:
tensor1 = torch.randn(10,3,2)
tensor2 = torch.randn(10,2,4)
print("a = ", tensor1)
print("b = ",tensor2)
result = torch.bmm(tensor1, tensor2)
print("Matrix Multiplication")
print("result = ", result)
print("result shape = ", result.shape)

a =  tensor([[[ 1.4831, -0.1337],
         [ 0.3855, -0.7183],
         [-1.0251,  1.1035]],

        [[ 0.5964,  0.6594],
         [-0.3277, -0.0306],
         [ 1.5217,  0.1057]],

        [[-0.3628, -1.0598],
         [-1.9851,  1.8015],
         [ 0.1152,  1.6164]],

        [[ 0.0255, -1.4810],
         [ 1.5431,  0.9549],
         [ 0.6152,  1.8075]],

        [[-0.5262, -1.2462],
         [-1.3657, -0.3270],
         [ 0.8826,  1.8612]],

        [[-0.3312, -1.3905],
         [ 2.1238,  0.8739],
         [ 1.9019, -0.1205]],

        [[-1.0616, -0.6326],
         [ 0.0627, -0.9063],
         [-2.0943,  0.6003]],

        [[-0.4176, -0.9608],
         [ 0.1153, -0.7659],
         [ 0.8814, -2.1365]],

        [[ 0.6040, -0.7310],
         [-0.0928,  0.0083],
         [ 0.0389, -2.5187]],

        [[-0.5384,  0.7085],
         [-1.3090, -0.6554],
         [-1.2515,  0.4017]]])
b =  tensor([[[ 0.7895,  0.8555, -0.0267, -0.6621],
         [ 0.6705, -1.8770,  0.7008, -0.8564]],

    

# Matrix Multiplication in Tensorflow
1. ## tf.matmul()

a. If both matrices are 1-dimensional, the dot product (scalar) is returned

In [ ]:

A1 = tf.constant([[2]])
B1 = tf.constant([[2]])
C1 = tf.matmul(A1, B1)
print(C1)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)



b. 
- This function doesn't allow broadcasting
- If input is a $(n x m)$ matrix, mat2 is a $(m x p)$ matrix, out will be a $(n x p)$ matrix


In [ ]:

A1 = tf.constant([[2, 24], [2, 26], [2, 57]])
B1 = tf.constant([[1000], [1500]])
print("A1=", A1)
print("B1=",B1)
print("Matrix Multiplication")
C1 = tf.matmul(A1, B1)
print("Result=",C1)

A1= tf.Tensor(
[[ 2 24]
 [ 2 26]
 [ 2 57]], shape=(3, 2), dtype=int32)
B1= tf.Tensor(
[[1000]
 [1500]], shape=(2, 1), dtype=int32)
Matrix Multiplication
Result= tf.Tensor(
[[38000]
 [41000]
 [87500]], shape=(3, 1), dtype=int32)


# Matrix Multiplication in Numpy 

1. np.dot()
2. np.matmul()
3. np.multiply()
 

In [ ]:
A = np.random.randint(10,size=(100,100))
B = np.random.randint(10,size=(100,100))


If we take dot product of two matrices $A_{nxm}$.$B_{mxn}$ then the product is $C_{nxn}$.

In [ ]:
start=pt()
C=np.dot(A,B)
end=pt()
print("A= ",A)
print("B= ",B)
print("Matrix Multiplication")
print("C= ",C)
print("Size of result matrix",C.shape)
print("Memory Consumption", sys.getsizeof(C)," bytes.")
print("Computation Time Required", end-start," seconds.")

A=  [[6 1 9 ... 3 3 9]
 [4 4 8 ... 0 4 2]
 [5 1 1 ... 1 2 4]
 ...
 [3 8 5 ... 0 6 5]
 [1 5 4 ... 0 2 8]
 [5 0 8 ... 5 4 2]]
B=  [[2 5 8 ... 5 9 7]
 [9 1 1 ... 6 2 5]
 [6 0 8 ... 2 0 1]
 ...
 [4 2 8 ... 5 2 3]
 [7 1 8 ... 3 1 4]
 [7 3 3 ... 9 6 6]]
Matrix Multiplication
C=  [[2250 1999 2422 ... 2416 2512 2334]
 [1913 1581 2113 ... 2103 2034 2046]
 [2043 2112 2119 ... 2276 2385 2033]
 ...
 [2196 1854 2306 ... 2478 2341 2297]
 [1932 1782 1985 ... 2180 2166 1907]
 [1937 1764 2070 ... 2070 1941 2077]]
Size of result matrix (100, 100)
Memory Consumption 80120  bytes.
Computation Time Required 0.002966546999999764  seconds.


Matrix multiplication of two matrices $A_{nxm}$.$B_{mxn}$ with np.matmul() method results in $C_{nxn}$   

This method is useful when the dimensionlity of matrices is not well defined. 

In [ ]:
start=pt()
C=np.matmul(A,B)
end=pt()
print("A= ",A)
print("B= ",B)
print("Matrix Multiplication")
print("C= ",C)
print("Size of result matrix",C.shape)
print("Memory Consumption", sys.getsizeof(C)," bytes.")
print("Computation Time Required", end-start," seconds.")

A=  [[6 1 9 ... 3 3 9]
 [4 4 8 ... 0 4 2]
 [5 1 1 ... 1 2 4]
 ...
 [3 8 5 ... 0 6 5]
 [1 5 4 ... 0 2 8]
 [5 0 8 ... 5 4 2]]
B=  [[2 5 8 ... 5 9 7]
 [9 1 1 ... 6 2 5]
 [6 0 8 ... 2 0 1]
 ...
 [4 2 8 ... 5 2 3]
 [7 1 8 ... 3 1 4]
 [7 3 3 ... 9 6 6]]
Matrix Multiplication
C=  [[2250 1999 2422 ... 2416 2512 2334]
 [1913 1581 2113 ... 2103 2034 2046]
 [2043 2112 2119 ... 2276 2385 2033]
 ...
 [2196 1854 2306 ... 2478 2341 2297]
 [1932 1782 1985 ... 2180 2166 1907]
 [1937 1764 2070 ... 2070 1941 2077]]
Size of result matrix (100, 100)
Memory Consumption 80120  bytes.
Computation Time Required 0.0021940929999999526  seconds.


The matrix multiplication of two matrices using np.multiply() method performs element-wise multiplication on them.  When using this method, both matrices should have the same dimensions.

$A_{nxm}$x$B_{mxn}$  is possible only when m=n

In [ ]:

start=pt()
C=np.multiply(A,B)
end=pt()
print("A= ",A)
print("B= ",B)
print("Matrix Multiplication")
print("C= ",C)
print("Size of result matrix",C.shape)
print("Memory Consumption", sys.getsizeof(C)," bytes.")
print("Computation Time Required", end-start," seconds.")

A=  [[6 1 9 ... 3 3 9]
 [4 4 8 ... 0 4 2]
 [5 1 1 ... 1 2 4]
 ...
 [3 8 5 ... 0 6 5]
 [1 5 4 ... 0 2 8]
 [5 0 8 ... 5 4 2]]
B=  [[2 5 8 ... 5 9 7]
 [9 1 1 ... 6 2 5]
 [6 0 8 ... 2 0 1]
 ...
 [4 2 8 ... 5 2 3]
 [7 1 8 ... 3 1 4]
 [7 3 3 ... 9 6 6]]
Matrix Multiplication
C=  [[12  5 72 ... 15 27 63]
 [36  4  8 ...  0  8 10]
 [30  0  8 ...  2  0  4]
 ...
 [12 16 40 ...  0 12 15]
 [ 7  5 32 ...  0  2 32]
 [35  0 24 ... 45 24 12]]
Size of result matrix (100, 100)
Memory Consumption 80120  bytes.
Computation Time Required 0.00018374499999929128  seconds.
